In [1]:
#imports 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df=pd.read_csv("movies.csv")
print(df.index)
print("All columns are")
ai=0
for i in df:
    print(ai,i)
    ai+=1

RangeIndex(start=0, stop=9742, step=1)
All columns are
0 Id
1 Title
2 Genres

In [3]:
df.shape

(9742, 3)

In [4]:
df.head()

,Id,Title,Genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      9742 non-null   int64
 1   Title   9742 non-null   object
 2   Genres  9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [6]:

tdf = pd.read_csv("movies.csv")

In [7]:
# Convert genres into 0/1 columns
tgenreFeatures = tdf["Genres"].str.get_dummies(sep="|")

In [8]:
print(tgenreFeatures)

      (no genres listed)  Action  Adventure  Animation  Children  Comedy  \
0                      0       0          1          1         1       1
1                      0       0          1          0         1       0
2                      0       0          0          0         0       1
3                      0       0          0          0         0       1
4                      0       0          0          0         0       1
...                  ...     ...        ...        ...       ...     ...
9737                   0       1          0          1         0       1
9738                   0       0          0          1         0       1
9739                   0       0          0          0         0       0
9740                   0       1          0          1         0       0
9741                   0       0          0          0         0       1

      Crime  Documentary  Drama  Fantasy  Film-Noir  Horror  IMAX  Musical  \
0         0            0      0        1          0       0     0        0
1         0            0      0        1          0       0     0        0
2         0            0      0        0          0       0     0        0
3         0            0      1        0          0       0     0        0
4         0            0      0        0          0       0     0        0
...     ...          ...    ...      ...        ...     ...   ...      ...
9737      0            0      0        1          0       0     0        0
9738      0            0      0        1          0       0     0        0
9739      0            0      1        0          0       0     0        0
9740      0            0      0        0          0       0     0        0
9741      0            0      0        0          0       0     0        0

      Mystery  Romance  Sci-Fi  Thriller  War  Western
0           0        0       0         0    0        0
1           0        0       0         0    0        0
2           0        1       0         0    0        0
3           0        1       0         0    0        0
4           0        0       0         0    0        0
...       ...      ...     ...       ...  ...      ...
9737        0        0       0         0    0        0
9738        0        0       0         0    0        0
9739        0        0       0         0    0        0
9740        0        0       0         0    0        0
9741        0        0       0         0    0        0

[9742 rows x 20 columns]

In [10]:
tgenreFeatures.head()

,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [12]:
# Checking if a movie has no genre listed
a=1
for i in (tgenreFeatures['(no genres listed)']):
    if i==1:
        print('No genre listed in column',a)
    a+=1

No genre listed in column 8518
No genre listed in column 8685
No genre listed in column 8688
No genre listed in column 8783
No genre listed in column 8837
No genre listed in column 8903
No genre listed in column 9034
No genre listed in column 9054
No genre listed in column 9071
No genre listed in column 9092
No genre listed in column 9139
No genre listed in column 9179
No genre listed in column 9218
No genre listed in column 9249
No genre listed in column 9260
No genre listed in column 9308
No genre listed in column 9317
No genre listed in column 9349
No genre listed in column 9414
No genre listed in column 9427
No genre listed in column 9449
No genre listed in column 9479
No genre listed in column 9515
No genre listed in column 9516
No genre listed in column 9519
No genre listed in column 9526
No genre listed in column 9535
No genre listed in column 9542
No genre listed in column 9563
No genre listed in column 9574
No genre listed in column 9612
No genre listed in column 9662
No genre listed in column 9664
No genre listed in column 9670

In [18]:
# Lets drop these columns then perform the split
# Checking if a movie has no genre listed

movies = df[df['Genres'] != '(no genres listed)']
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9708 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      9708 non-null   int64
 1   Title   9708 non-null   object
 2   Genres  9708 non-null   object
dtypes: int64(1), object(2)
memory usage: 303.4+ KB

In [19]:
# Convert genres into 0/1 columns
genreFeatures = ddf["Genres"].str.get_dummies(sep="|")

In [20]:
print(genreFeatures)

      Action  Adventure  Animation  Children  Comedy  Crime  Documentary  \
0          0          1          1         1       1      0            0
1          0          1          0         1       0      0            0
2          0          0          0         0       1      0            0
3          0          0          0         0       1      0            0
4          0          0          0         0       1      0            0
...      ...        ...        ...       ...     ...    ...          ...
9737       1          0          1         0       1      0            0
9738       0          0          1         0       1      0            0
9739       0          0          0         0       0      0            0
9740       1          0          1         0       0      0            0
9741       0          0          0         0       1      0            0

      Drama  Fantasy  Film-Noir  Horror  IMAX  Musical  Mystery  Romance  \
0         0        1          0       0     0        0        0        0
1         0        1          0       0     0        0        0        0
2         0        0          0       0     0        0        0        1
3         1        0          0       0     0        0        0        1
4         0        0          0       0     0        0        0        0
...     ...      ...        ...     ...   ...      ...      ...      ...
9737      0        1          0       0     0        0        0        0
9738      0        1          0       0     0        0        0        0
9739      1        0          0       0     0        0        0        0
9740      0        0          0       0     0        0        0        0
9741      0        0          0       0     0        0        0        0

      Sci-Fi  Thriller  War  Western
0          0         0    0        0
1          0         0    0        0
2          0         0    0        0
3          0         0    0        0
4          0         0    0        0
...      ...       ...  ...      ...
9737       0         0    0        0
9738       0         0    0        0
9739       0         0    0        0
9740       0         0    0        0
9741       0         0    0        0

[9708 rows x 19 columns]

In [26]:
print(genreFeatures.columns)

Index(['Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'IMAX',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War',
       'Western'],
      dtype='object')

In [21]:
# Computing cosine similarity between all movies

similarityMatrix = cosine_similarity(genreFeatures)

In [28]:
similarityMatrix.shape

(9708, 9708)

In [29]:
# Converting to DataFrame for easier indexing

similarityDf = pd.DataFrame(
    similarityMatrix,
    index=movies["Title"],
    columns=movies["Title"]
)

similarityDf.head()

Title,Toy Story (1995),Jumanji (1995),Grumpier Old Men (1995),Waiting to Exhale (1995),Father of the Bride Part II (1995),Heat (1995),Sabrina (1995),Tom and Huck (1995),Sudden Death (1995),GoldenEye (1995),...,Gintama: The Movie (2010),anohana: The Flower We Saw That Day - The Movie (2013),Silver Spoon (2014),Love Live! The School Idol Movie (2015),Jon Stewart Has Left the Building (2015),Black Butler: Book of the Atlantic (2017),No Game No Life: Zero (2017),Flint (2017),Bungo Stray Dogs: Dead Apple (2018),Andrew Dice Clay: Dice Rules (1991)
Title,,,,,,,,,,,,,,,,,,,,,
Toy Story (1995),1.000000,0.774597,0.316228,0.258199,0.447214,0.0,0.316228,0.632456,0.0,0.258199,...,0.447214,0.316228,0.316228,0.447214,0.0,0.670820,0.774597,0.00000,0.316228,0.447214
Jumanji (1995),0.774597,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.816497,0.0,0.333333,...,0.000000,0.000000,0.000000,0.000000,0.0,0.288675,0.333333,0.00000,0.000000,0.000000
Grumpier Old Men (1995),0.316228,0.000000,1.000000,0.816497,0.707107,0.0,1.000000,0.000000,0.0,0.000000,...,0.353553,0.000000,0.500000,0.000000,0.0,0.353553,0.408248,0.00000,0.000000,0.707107
Waiting to Exhale (1995),0.258199,0.000000,0.816497,1.000000,0.577350,0.0,0.816497,0.000000,0.0,0.000000,...,0.288675,0.408248,0.816497,0.000000,0.0,0.288675,0.333333,0.57735,0.000000,0.577350
Father of the Bride Part II (1995),0.447214,0.000000,0.707107,0.577350,1.000000,0.0,0.707107,0.000000,0.0,0.000000,...,0.500000,0.000000,0.707107,0.000000,0.0,0.500000,0.577350,0.00000,0.000000,1.000000

In [31]:
# Function to recommend movies
def recommend(movieTitle, topN=10):
    
    if movieTitle not in similarityDf.index:
        return "Movie not found."

    scores = similarityDf[movieTitle]

    scores = scores.drop(movieTitle)

    recommendations = scores.sort_values(ascending=False).head(topN)

    return recommendations

In [32]:
# Now our function is made let's test it
# Suppose someone just watched Toy Story then what movies should be recommended
print(recommend("Toy Story (1995)"))

Title
Turbo (2013)                                               1.0
Tale of Despereaux, The (2008)                             1.0
Monsters, Inc. (2001)                                      1.0
Antz (1998)                                                1.0
Asterix and the Vikings (Astérix et les Vikings) (2006)    1.0
Shrek the Third (2007)                                     1.0
Emperor's New Groove, The (2000)                           1.0
Adventures of Rocky and Bullwinkle, The (2000)             1.0
Toy Story 2 (1999)                                         1.0
The Good Dinosaur (2015)                                   1.0
Name: Toy Story (1995), dtype: float64

In [36]:
print(recommend("Home (2015)"))

Title
Space Jam (1996)                                   1.000000
Robots (2005)                                      0.925820
Toy Story (1995)                                   0.912871
Moana (2016)                                       0.912871
Shrek the Third (2007)                             0.912871
Toy Story 2 (1999)                                 0.912871
Tale of Despereaux, The (2008)                     0.912871
Planet 51 (2009)                                   0.912871
Honey, I Shrunk the Kids (1989)                    0.912871
Grand Day Out with Wallace and Gromit, A (1989)    0.912871
Name: Home (2015), dtype: float64

In [37]:
print(recommend("Shrek (2001)"))

Title
Puss in Boots (Nagagutsu o haita neko) (1969)              1.000000
Gnomeo & Juliet (2011)                                     1.000000
Enchanted (2007)                                           0.925820
Toy Story (1995)                                           0.912871
Kid in King Arthur's Court, A (1995)                       0.912871
Asterix and the Vikings (Astérix et les Vikings) (2006)    0.912871
Monsters, Inc. (2001)                                      0.912871
Shrek the Third (2007)                                     0.912871
Moana (2016)                                               0.912871
Wild, The (2006)                                           0.912871
Name: Shrek (2001), dtype: float64